#!/bin/sh
# simple dmenu power menu

#DMENU='dmenu -i -c -g 1 -l 4 -fn IBMPlexMono:semibold:size=12 -nb #000000 -p Power:'
DMENU='dmenu -i -fn IBMPlexMono:semibold:size=12 -nb #000000 -p Power:'
choice=$(echo -e "sleep\nlock\nlogout\nreboot\nshutdown" | $DMENU)

case "$choice" in
	lock) ~/.scripts/lock;;
	sleep) ~/.scripts/sleeplock ;;
	logout) killall dwm ;;
	reboot) reboot ;;
	shutdown) shutdown now ;;
esac
